# Generated by Django 3.1.13 on 2021-09-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210923_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Account_type',
            new_name='account_type',
        ),
    ]
