# Generated by Django 3.1.13 on 2021-09-24 12:52

import afriproperty.users.models
import django.core.validators
from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210923_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='about',
            field=tinymce.models.HTMLField(blank=True, max_length=255, null=True, verbose_name='Why should they work with you?'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[300, 300], upload_to=afriproperty.users.models.profile_image),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, help_text='https://www.facebook.com/username/', null=True, unique=True, verbose_name='Facebook Profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='googleplus',
            field=models.URLField(blank=True, help_text='https://www.google.com/profilename/', null=True, unique=True, verbose_name='Google Plus Profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, help_text='https://www.linkedin.com/in/username/', null=True, unique=True, verbose_name='Linkedin Profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
    ]
