# Generated by Django 3.1.13 on 2021-09-24 13:14

import afriproperty.users.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210924_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[300, 300], upload_to=afriproperty.users.models.profile_image),
        ),
    ]
