# Generated by Django 3.1.13 on 2021-09-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210925_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=700, null=True, unique=True),
        ),
    ]
