# Generated by Django 3.1.13 on 2021-10-03 13:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211001_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='about',
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True, verbose_name='Why should they work with you?'),
        ),
    ]
