# Generated by Django 3.1.13 on 2021-09-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
