# Generated by Django 3.1.13 on 2021-10-10 13:55

import afriproperty.tips.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_tip_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipimagefile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', help_text='image size: 520x397.', keep_meta=True, null=True, quality=80, size=[520, 397], upload_to=afriproperty.tips.models.tip_images),
        ),
    ]
