# Generated by Django 3.1.13 on 2021-09-24 16:34

import afriproperty.property.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('property_title', models.CharField(max_length=500, null=True, verbose_name='Property Title')),
                ('slug', models.SlugField(blank=True, max_length=700, null=True, unique=True)),
                ('property_status', models.CharField(blank=True, choices=[('Sold', 'Sold'), ('Buy', 'Buy'), ('Rent', 'Rent'), ('Develop', 'Develop'), ('Shortlet', 'Shortlet')], default='Rent', max_length=8, null=True, verbose_name='Property Status')),
                ('property_type', models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Commercial', 'Commercial'), ('Garage', 'Garage'), ('Lot', 'Lot'), ('Plot', 'Plot')], default='Apartment', max_length=11, null=True, verbose_name='Property Type')),
                ('property_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Property Price')),
                ('property_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Area Sq/Ft')),
                ('property_rooms', models.IntegerField(blank=True, choices=[(1, '1  Room'), (2, '2  Rooms'), (3, '3  Rooms'), (4, '4  Rooms'), (5, '5  Rooms'), (0, 'More than 5 Rooms')], default=1, null=True, verbose_name='Rooms')),
                ('property_location', models.CharField(max_length=500, null=True, verbose_name='Address')),
                ('property_state', models.CharField(max_length=500, null=True, verbose_name='State')),
                ('property_detail', tinymce.models.HTMLField()),
                ('property_age', models.CharField(blank=True, choices=[('0 - 1', '0 - 1'), ('0 - 5', '0 - 5'), ('0 - 10', '0 - 10'), ('0 - 20', '0 - 20'), ('0 - 50', '0 - 50'), ('50 - more', '50 - more')], default='0 - 5', max_length=50, null=True, verbose_name='Building Age (Optional)')),
                ('property_features', models.CharField(blank=True, choices=[('Air Conditioning', 'Air Conditioning'), ('Swimming Pool', 'Swimming Pool'), ('Central Heating', 'Central Heating'), ('Laundry Room', 'Laundry Room'), ('Gym', 'Gym'), ('Alarm', 'Alarm')], default='Swimming Pool', max_length=17, null=True, verbose_name='Location')),
                ('approved', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('property_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentproperty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created', 'property_title'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PropertyImageField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.FileField(upload_to=afriproperty.property.models.property_images)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyimage', to='property.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
