# Generated by Django 3.1.13 on 2021-09-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_price_type',
            field=models.CharField(blank=True, choices=[('Annually', 'Annually'), ('Monthly', 'Monthly'), ('Sq/Ft', 'Sq/Ft')], default='Annually', max_length=15, null=True, verbose_name='Property Price Type'),
        ),
    ]
