# Generated by Django 3.1.13 on 2021-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_property_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_near_location',
            field=models.CharField(max_length=500, null=True, verbose_name='Property Closest to Listing'),
        ),
    ]
