# Generated by Django 3.1.13 on 2021-09-26 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_auto_20210925_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=70, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=70, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_rooms',
        ),
        migrations.AddField(
            model_name='property',
            name='property_area_number',
            field=models.IntegerField(blank=True, default=0, help_text='use 1 to indicate the total number of quare feets you have for sale or rent from 1-1000.', null=True, verbose_name="Landed Propert's Total Agrea to be multiplied by for Area (Sq/Ft)"),
        ),
        migrations.AddField(
            model_name='property',
            name='property_bedrooms',
            field=models.IntegerField(choices=[(1, '1  Room'), (2, '2  Rooms'), (3, '3  Rooms'), (4, '4  Rooms'), (5, '5  Rooms'), (0, 'More than 5 Rooms')], default=1, null=True, verbose_name='Bed Rooms'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_parlors',
            field=models.IntegerField(choices=[(1, '1  Room'), (2, '2  Rooms'), (3, '3  Rooms'), (4, '4  Rooms'), (5, '5  Rooms'), (0, 'More than 5 Rooms')], default=1, null=True, verbose_name='Parlors'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_features',
            field=models.ManyToManyField(help_text='Select all features that apply for the house', to='property.PropertyFeature'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='if your price type is sq/ft, then the price cost should be by a unit of the property area square feet and leave the total we will automatically round it up for you by the total area numbers you have ', max_digits=20, verbose_name='Property Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_state',
            field=models.CharField(help_text='eg. Abuja zipcode  !!! PS: this should just be the state and zipcode only !!!', max_length=500, null=True, verbose_name='State of properties'),
        ),
        migrations.CreateModel(
            name='PropertySearchSaved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('search_link', models.URLField(blank=True, null=True)),
                ('saved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Search Query',
                'verbose_name_plural': 'Properties Search Query',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PropertyCompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, default='result', max_length=800, null=True, unique=True)),
                ('p_one', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcompareone', to='property.property')),
                ('p_three', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcomparethree', to='property.property')),
                ('p_two', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcomparetwo', to='property.property')),
            ],
            options={
                'verbose_name': 'Property Compare',
                'verbose_name_plural': 'Properties Compared',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PropertyBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active', models.BooleanField(default=False)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarkproperty', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarkuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Bookmark',
                'verbose_name_plural': 'Properties Bookmarked',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propertycity', to='property.city'),
        ),
    ]
