# Generated by Django 3.1.13 on 2021-09-26 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20210926_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propertystate', to='property.state'),
        ),
    ]
