# Generated by Django 3.1.13 on 2021-09-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20210926_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True, 'ordering': ['title'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'managed': True, 'ordering': ['title'], 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterField(
            model_name='property',
            name='property_area',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Area Sq/Ft'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_price',
            field=models.PositiveBigIntegerField(default=0, help_text='if your price type is sq/ft, then the price cost should be by a unit of the property area square feet and leave the total we will automatically round it up for you by the total area numbers you have ', verbose_name='Property Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Commercial', 'Commercial'), ('Garage', 'Garage'), ('Garden', 'Garden'), ('Lot', 'Lot'), ('Plot', 'Plot')], default='Apartment', max_length=11, null=True, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='state',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
