# Generated by Django 3.1.13 on 2021-09-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20210928_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
