# Generated by Django 3.1.13 on 2021-09-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20210928_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyfeature',
            options={'managed': True, 'ordering': ['property_features'], 'verbose_name': 'Property Feature', 'verbose_name_plural': 'Property Features'},
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
