# Generated by Django 3.1.13 on 2021-09-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20210928_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='Per Sq/Ft'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_area_number',
            field=models.IntegerField(blank=True, default=1, help_text='From 1-1000. to calculate to total price for square feets', null=True, verbose_name='How many sq/ft do you have of the above property per sq/ft? i.e (5 Per Sq/Ft x 10 = 50 Total Square Feet) leave it empty for rented properties'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_expire',
            field=models.IntegerField(blank=True, default=0, help_text='use 100 if it a land that is being purchased. and any figure when it is a rentage. NOTE: An additional 2 months is given to a property before it is reactivated as availble for purchase after its last purchased date', null=True, verbose_name='How long is the renting or buying supposed to last, 1 year or more?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_location',
            field=models.CharField(help_text='eg. 123 Close, Street  !!! PS: Do not attach a state or country when listing this property !!!', max_length=500, null=True, verbose_name='Property Street Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='if your price type is sq/ft, then the price cost should be by a unit of the property area square feet and leave the total we will automatically round it up for you by the total area numbers you have ', max_digits=20, verbose_name='Property Price (for 1 year or 1 sq/ft)'),
        ),
        migrations.AlterField(
            model_name='propertyblueprint',
            name='type',
            field=models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('First Floor', 'First Floor'), ('Second Floor', 'Second Floor'), ('Third Floor', 'Third Floor'), ('Fourth Floor', 'Fourth Floor'), ('All Floor Type', 'All Floor Type'), ('Penthouse', 'Penthouse'), ('Garage', 'Garage'), ('Pool House', 'Pool House')], default='First Floor', max_length=50, null=True, verbose_name='Blueprint'),
        ),
    ]
