# Generated by Django 3.1.13 on 2021-10-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20211003_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Commercial', 'Commercial'), ('Garage', 'Garage'), ('Garden', 'Garden'), ('Lot', 'Lot'), ('Plot', 'Plot')], default='Apartment', max_length=15, null=True, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='propertycompare',
            name='property',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compareproperty', to='property.property'),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='property_features',
            field=models.CharField(blank=True, choices=[('Air Conditioning', 'Air Conditioning'), ('Swimming Pool', 'Swimming Pool'), ('Central Heating', 'Central Heating'), ('Laundry Room', 'Laundry Room'), ('Parking Lot', 'Parking Lot'), ('Exercise Room', 'Exercise Room'), ('Central Cooling', 'Central Cooling'), ('Srorage Room', 'Srorage Room'), ('Treated Water', 'Treated Water'), ('Internet', 'Internet'), ('Garage', 'Attached Garage'), ('Garden', 'Garden'), ('Gym', 'Gym'), ('Alarm', 'Alarm')], default='Swimming Pool', max_length=17, null=True, unique=True, verbose_name='Property Features (Optional)'),
        ),
    ]
