# Generated by Django 3.1.13 on 2021-10-12 07:48

import afriproperty.property.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20211010_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyblueprint',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='image size: 1000x576.', keep_meta=True, null=True, quality=70, size=[1000, 576], upload_to=afriproperty.property.models.blueprint_image),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='image size: 520x397.', keep_meta=True, null=True, quality=80, size=[520, 397], upload_to=afriproperty.property.models.property_images),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(blank=True, help_text='Your video should be 40Seconds Long, 20MB in size max', null=True, upload_to=afriproperty.property.models.property_video),
        ),
    ]
